#version: '3.8'

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME:-dealls}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-d3alls}
      POSTGRES_DB: ${DB_DATABASE:-be_dealls}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  payroll_app:
    build:
      context: payroll_app
      dockerfile: Dockerfile
      args:
        NODE_ENV: ${NODE_ENV:-development}
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    volumes:
      - ./payroll_app:/usr/src/app
    environment:
      DB_HOST: ${DB_HOST:-postgres}
      DB_PORT: 5432
      DB_USERNAME: ${DB_USERNAME:-dealls}
      DB_PASSWORD: ${DB_PASSWORD:-d3alls}
      DB_DATABASE: ${DB_DATABASE:-be_dealls}
      NODE_ENV: ${NODE_ENV:-development}
    command: >
      sh -c "
      if [ '${NODE_ENV}' = 'production' ]; then
        npm run start:prod;
      else
        npm run start:dev;
      fi
      "

volumes:
  pgdata:

